### ISSUE TITLE
Png meta

### ISSUE THREAD

**Issue by kin30528** [alexeiskachykhin/obsidian-image-metadata-plugin#1]
It would be nice if we could set the mata for png as well. 
Thanks for making the plugin, I've been wanting it for a long time~~

**Comment by alexeiskachykhin** [comment]
Hey @kin30528 thank you for your feedback. I'm looking into PNG support right now.

**Comment by alexeiskachykhin** [comment]
@kin30528 thank you for waiting. I just released version 1.1.0 that supports PNG. Give it a shot ;)

**Comment by kin30528** [comment]
> @kin30528 thank you for waiting. I just released version 1.1.0 that supports PNG. Give it a shot ;)

wonderful, thank u~~
