### ISSUE TITLE
[Feature Request] Support for .webp format

### ISSUE THREAD

**Issue by WangWuxiucheng** [alexeiskachykhin/obsidian-image-metadata-plugin#2]
Hi alexeiskachykhin,

Thank you for creating this Obsidian plugin! The ability to add information to attached images is quite useful, especially for adding reference notes, captions, and backtracing. 

I am wondering if you might consider adding support for .webp image format to the plugin? 

Thank you again for your efforts on this plugin!

Best regards,
W. Wang

**Comment by alexeiskachykhin** [comment]
Hey @WangWuxiucheng, thank you! Its great to hear that you find it useful. I went ahead and added WEBP support in version 1.2.0. Please let me know if you run into any issues.

Have a great day!

**Comment by WangWuxiucheng** [comment]
Hi @alexeiskachykhin 

Thank you very much for the swift update. I have upgraded the plugin to Ver.1.2.0 and tested it with a few .webp images in my Obsidian notes. The new update works well. I have verified that the metadata (XMP:DC Description) is correctly attached to the .webp files using ExifToolGui. 👍

---

I've noticed that the metadata attaches to the Title property in .png files and the Subject property in .jpg files. However, for the new .webp update, the attached metadata is not visible to regular users without tools like ExifToolGui.

Here are the great features of your image metadata plugin (which works very well with .jpg and .png formats):

1.   It allows adding descriptive notes, captions, and reference information to images during note editing, enabling more complex strings than just the filename. This workflow is much smoother with your plugin than manually editing the image properties externally.
2.   I can view the descriptions in Windows Explorer and the file property window.
3.   I can use 'Everything (1.5a)' to search file descriptions via keywords (verified on .png and .jpg).

Perhaps in a future version, the metadata for .webp images could be attached to a property that is visible in Windows Explorer and searchable with 'Everything (1.5a)'. I believe these enhancements would benefit other users as well.

Thanks!

**Comment by alexeiskachykhin** [comment]
@WangWuxiucheng thank you testing it and your feedback. By any chance, do you have an example of webp file with metadata visible in Windows Explorer?

**Comment by WangWuxiucheng** [comment]
Hi @alexeiskachykhin,

I tested three images, experimented and attached most of the EXIF & XMP info to them (using this webtool: www.thexifer.net). I found the `XMP:Title` property works well for three image formats.

Here is a screenshot of the file properties for three test images:
![image](https://github.com/user-attachments/assets/b6b20694-4058-42a7-8f89-c310dbf2b0cc)

Here is a screenshot of the windows explorer window:
![image](https://github.com/user-attachments/assets/8a0b6b9d-efa1-45a9-9caa-dc69f43cddf2)

Screenshot of Everything search software:
![image](https://github.com/user-attachments/assets/598a19d3-273e-48b6-a01f-cc0449ebf74d)


I hope this could save you some time. 
Test images attached here. 
[Test_Images.zip](https://github.com/user-attachments/files/17711979/Test_Images.zip)

Thank you!
W.Wang
